### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by bardware** [KamasamaK/vscode-cfml#10]
Hi,

I just took notice of the fact there are plugins that display Outlines of code files like: https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline.
Can your plugin tokenize CFML code and fill an Outline view?

Similar issues in other projects
https://github.com/Microsoft/vscode-go/issues/919
https://github.com/Microsoft/vscode/issues/5605

**Comment by KamasamaK** [comment]
This extension provides Document Symbols, which are used to populate the outline view in [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline). The Code Outline extension is actually one of my [Recommended Extensions](https://github.com/KamasamaK/vscode-cfml#recommended-extensions) since it is not yet integrated into VS Code, though as you pointed out is one of the most requested features.

**Comment by bardware** [comment]
Thanks for the explanation. I had your extension active and the Outline plugin installed but it stayed empty. I don't understand why and how but in the meantime I saw it working.
In a cfc I saw the functions and even a couple tokens in the function. Works nicely. Thanks alot.
