### ISSUE TITLE
As soon as plugin is installed 64 bit VS code windows 10 VS code becomes unresponsive

### ISSUE THREAD

**Issue by shakeelosmani** [KamasamaK/vscode-cfml#2]
@KamasamaK 

Hi, I know you and illya are working out how you guys are going to proceed further, seeing the symbol help I jumped in and installed on my VS Code instance but the Editor immediately crawled into unresponsiveness.
Any idea why that would happen
![image](https://user-images.githubusercontent.com/9120484/31284533-d766d6b2-aa86-11e7-8da5-722988e2392e.png)

I have attached list plugins that I used. Mind you I removed Illya's plugin when I had installed yours.

Thanks

**Comment by KamasamaK** [comment]
For how long does it remain unresponsive? This is likely due to the indexing of components, which can be disabled, but will disable most features such as workspace symbols. Can you tell me about how many CFC files you have? What are the specs on your machine? I only notice a few seconds on startup, but I can see it being a lengthy process with thousands. That would only worsen if you don't have an SSD.

I wasn't able to find any of those extensions causing it. Although disabling each and testing would help determine for you. Just FYI, some of those seem unnecessary to me.

`Coldfusion commentation` is no longer needed since the integrated comments are contextual now and have commands for which you can rebind the keys if you don't like the defaults.
`Prettify JSON` seems to perform the same/similar action as Format Document (`Alt+Shift+F`)
`Untabify` seems to perform the same actions as the the indentation commands built into VS Code

**Comment by sosensible** [comment]
We have multiple devs using this without that issue. I don't doubt it happened but it works great at our company.

**Comment by shakeelosmani** [comment]
This is solved thanks :)
