### ISSUE TITLE
Element completions and suggestions don't work as expected

### ISSUE THREAD

**Issue by WebVeteran** [KamasamaK/vscode-cfml#24]
Adding CFML tags don't:
* suggest tags while typing
* wrap selected suggestion attributes in quotes
* auto close only when "</" is entered (it happens as soon as you enter ">"
* auto indent the next line

Adding a HTML tags do:
* suggest tags while typing
* wrap selected suggestion attributes in quotes
* auto close only when "</" is entered
* auto indent the next line

See attached zipped mp4.
[suggestions.mp4.zip](https://github.com/KamasamaK/vscode-cfml/files/2470177/suggestions.mp4.zip)

**Comment by KamasamaK** [comment]
Thanks for the video. Here are my responses:

1. Adding a CFML tag should
a. Suggest tags while typing: This has been a feature since the initial release. I'm not sure why it isn't working for you. The only thing I can think of is your `cfml.suggest.globalTags.enable` is not set to `true`.
b. Append quotes when completing suggested attributes: There is now a setting `cfml.suggest.globalTags.attributes.quoteType` for this which defaults to `double`.
c. Auto-close only when `</` is entered: This is handled by the `auto-close-tag` extension. See my response in #23.
d. Auto-indent the next line: The indentation should work this way in v0.5.0+.

**Comment by WebVeteran** [comment]
I updated VSC and extensions, so giving it another shot here.

a) It works. Though `cfml.suggest.globalTags.enable` was always set to `true`.
b) It works.
c) It works.
d) It works.

Awesome work @KamasamaK !
