### ISSUE TITLE
Highlight invalid comma after last array element

### ISSUE THREAD

**Issue by dominikbraun** [KamasamaK/vscode-cfml#34]
This is a new feature proposal.

In CFScript, the last element of an array isn't allowed to have a trailing comma. Trailing commas after the last element are considered as a syntax error.

`coffee = [  
	"Cappuccino",  
	"Espresso",  
	"Latte macchiato",
];`

This code will result in an error. Would it be great effort to highlight/underline the closing bracket in order to indicate that mistake?

**Comment by KamasamaK** [comment]
This only produces an error in Adobe ColdFusion. A trailing comma is valid in Lucee/Railo. Since the grammar is static and intended to work for all CFML engines, this cannot be done that way. It is possible to do this via diagnostics, but that is best delegated to the [CFLint extension](https://github.com/KamasamaK/vscode-cflint) currently. However, that extension uses CFParser, which does also support trailing commas. You may consider requesting a [CFLint rule](https://github.com/cflint/CFLint/issues) for something like this.

**Comment by dominikbraun** [comment]
I noticed that it works in Lucee/Railo and see that it is an issue for CFLint instead of the CFML plugin itself and therefore opened a issue. Thanks!
