### ISSUE TITLE
Comments - uncomment not working correctly

### ISSUE THREAD

**Issue by jimpriest** [KamasamaK/vscode-cfml#36]
If I comment a single line - I can then place my cursor within the comment and hit comment shortcut again and the comment is removed.  

If I select a block of text - I can hit comment, it's wrapped correctly:
```
Givin:
<div class="text">
      	#rc.getFoo()#
</div>

When I hit comment shortcut I get

<!--- <div class="text">
      	#rc.getFoo()#
</div>--->

Then if I place my cursor within the comment and hit comment again (I'd expect the comments to be removed) I get:

<!--- <div class="text">
   #rc.<!---  --->.getFoo()#
</div> ---> 

```

Tried with both CTRL+/ and CTRL+SHIFT+A

**Comment by KamasamaK** [comment]
Commenting is delegated to VS Code. The extension just defines what a line comment and block comment are. In order to undo a block comment, you must highlight the lines of the block just as you do to create the comment. The only issues I've encountered are with context-switching between the beginning and end of a block (e.g. start with CF tag and end with CF Script or JavaScript).

Try the same thing with a standard HTML and see if VS Code behaves differently.

NOTE: `Ctrl`+`Shift`+`A` is not a default shortcut for comments. Perhaps you mean `Shift`+`Alt`+`A`, which is for block comments.
